version: '3'
services:
  nodejs-server:
    build:
      context: ./api
    ports:
      - "3080:${API_PORT}"
    container_name: back-api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  react-ui:
    build:
      context: ./my-app
    ports:
      - "3000:${FRONT_PORT}"
    container_name: my-app
    stdin_open: true
    volumes:
       - ./my-app:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules