version: '3'
services:
  nodejs-server:
    build:
      context: ./api
    ports:
      - "3080:${API_PORT}"
    container_name: back-api
    environment:
      - BACK= ${API_PORT}
      - ENV= ${BACK_ENV}
    networks: 
      - my-application
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules

  react-ui:
    build:
      context: ./my-app
    ports:
      - "3000:${FRONT_PORT}"
    container_name: my-app
    environment:
      - REACT_APP_PORT= ${FRONT_PORT}
      - REACT_APP_API_URL= ${REACT_APP_API_URL}
      - ENV= ${FRONT_ENV}
    stdin_open: true
    networks: 
      - my-application
    volumes:
      - ./my-app:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules

  mongo-db:
    image: mongo:latest
    ports: 
      - "27017:27017"
    networks: 
      - my-application
    volumes: 
      - mongo-data:/data/db

networks: 
  my-application: 
    driver: bridge
volumes: 
  mongo-data: 
    driver: local